FROM rossbachp/presentation
MAINTAINER Peter Rossbach <peter.rossbach@bee42.com>

ADD images /opt/presentation/images
ADD md/slides.md /opt/presentation/lib/md/slides.md
COPY tomcat-reference.tar.gz /opt/presentation/lib/md/tomcat-reference.tar.gz
